// An application client is what would request access to a user account. 
var mongoose = require('mongoose');

var ClientSchema = new mongoose.Schema({
  name: { type: String, unique: true, required: true },
  id: { type: String, required: true },
  secret: { type: String, required: true },
  userId: { type: String, required: true }
});

//TODO: hash the secret.
// OR the id and secret can be autogenerated. 
// For now it is created straight from the PUT request.

module.exports = mongoose.model('Client', ClientSchema);